Vue.component("box-button", loadComponent("./component/button/index.vue"))
Vue.component("box-input", loadComponent("./component/input/index.vue"))
Vue.component("box-textarea", loadComponent("./component/textarea/index.vue"))
Vue.component("box-date-picker", loadComponent("./component/date-picker/index.vue"))
// Vue.component("box-layout", loadComponent("./component/layout/index.vue"))
// Vue.component("box-row", loadComponent("./component/row/index.vue"))
// Vue.component("box-col", loadComponent("./component/col/index.vue"))
Vue.component("box-form", loadComponent("./component/form/index.vue"))
Vue.component("box-form-item", loadComponent("./component/form-item/index.vue"))
// Vue.component("box-select", loadComponent("./component/select/index.vue"))
Vue.component("box-radio", loadComponent("./component/radio/index.vue"))
Vue.component("box-checkbox", loadComponent("./component/checkbox/index.vue"))
Vue.component("box-switch", loadComponent("./component/switch/index.vue"))
Vue.component("box-table", loadComponent("./component/table/index.vue"))
Vue.component("box-table2", loadComponent("./component/table2/index.vue"))
Vue.component("box-dialog", loadComponent("./component/dialog/index.vue"))
Vue.component("box-pagination", loadComponent("./component/pagination/index.vue"))
Vue.component("box-tabs", loadComponent("./component/tabs/index.vue"))
Vue.component("box-tab-pane", loadComponent("./component/tab-pane/index.vue"))
// Vue.component("box-progress", loadComponent("./component/progress/index.vue"))
// Vue.component("box-date-picker", loadComponent("./component/date-picker/index.vue"))
// Vue.component("box-pagination", loadComponent("./component/pagination/index.vue"))
Vue.component("box-select", loadComponent("./component/select/index.vue"))
Vue.component("box-tree", loadComponent("./component/tree/index.vue"))